version: '3.8'

services:
  translator-service:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
    - redis_data:/data

volumes:
  redis_data: